greystar@greystar-Lenovo-ThinkBook-14-IML:~/Downloads$ python3 quantum_chess.py
Exception in thread Thread-1 (net_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/greystar/Downloads/quantum_chess.py", line 450, in net_loop
    mv = self.recv_move()
         ^^^^^^^^^^^^^^^^
  File "/home/greystar/Downloads/quantum_chess.py", line 438, in recv_move
    return lan_socket.client_mode(b'', 'black', self.host_ip)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/greystar/Downloads/lan_socket.py", line 30, in client_mode
    return s.recv(1024).decode('utf-8')
           ^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
